### PR TITLE
Refactor 00075 dtypes

### LINKED ISSUE #75: Dtype consistency
dtype should come from the input tensor, but we need it sometimes at layer instantiation.  This would mean buffers are allocated on forward calls, which we may not want.

Current tests uses torch.Tensor which downcasts to float32, but torch.tensor keeps the dtype.

### PR DESCRIPTION
**Pull request by rhewett**
closes #75

### CODE REVIEW

**Comment by rhewett** [comment]
@jmerizia, in case this impacts your current work

**Review by thomasjgrady — CHANGES_REQUESTED** [review]
dtype checks are failing for test_broadcast.py. It looks like nan values are being created for some reason and pytorch is interpreting that dtype as int.

Command: mpirun --host localhost:20 -np 20 python -m mpi4py -m pytest -x --with-mpi -rsa tests
Output: ======================== 1 failed, 20 passed in 40.70s =========================
    assert y.dtype == dtype
E   assert torch.float32 == torch.int32
E    +  where torch.float32 = tensor([[[0.0000e+00, 5.6052e-45, 4.2039e-45,        nan,        nan],          [0.0000e+00,        nan,        nan, 1...     nan, 1.8217e-44,        nan,        nan],
[       nan, 9.8091e-45, 1.2612e-44,        nan,        nan]]]).dtype

**Comment by rhewett** [comment]
which test is that in?

**Comment by rhewett** [comment]
I'm not seeing where you made this specific comment, but I have an idea of the fix.  See the latest version of the PR and see if that resolves it.

**Comment by thomasjgrady** [comment]
It is failing at tests/test_broadcast.py::test_broadcast_dtype for me still with NaNs. I'm not sure if this is an issue of my system. Do the tests pass on your machine?

**Comment by rhewett** [comment]
It passes locally and on the CI.  But if you are having issues we need to be sure things work before merging.  I'm not even sure why you are getting NaNs.

**Comment by thomasjgrady** [comment]
I'm not really sure either, nor am I very sure how to start debugging this. My best guess is this could be a similar issue to the weird bugs you ran into when trying to implement the logic to exchange tensor sizes.  If this helps at all, here is my MPI specification as given by mpi4py.

MPI version: 3.1                                                                                                                                                                                           
MPI library version: Open MPI v4.0.3, package: Debian OpenMPI, ident: 4.0.3, repo rev: v4.0.3, Mar 03, 2020                                                                                                
MPI vendor: Open MPI 4.0.3                                                                                                                                                                                 
mpi4py rc:                                                                                                                                                                                                 
 initialize: True                                                                                                                                                                                          
 threads: True                                                                                                                                                                                             
 thread_level: multiple                                                                                                                                                                                    
 finalize: None                                                                                                                                                                                            
 fast_reduce: True                                                                                                                                                                                         
 recv_mprobe: True                                                                                                                                                                                         
 errors: exception                                                                                                                                                                                         
mpi4py config:                                                                                                                                                                                             
 mpicc: /usr/bin/mpicc                                                                                                                                                                                     
 mpicxx: /usr/bin/mpicxx                                                                                                                                                                                   
 mpifort: /usr/bin/mpifort                                                                                                                                                                                 
 mpif90: /usr/bin/mpif90                                                                                                                                                                                   
 mpif77: /usr/bin/mpif77

**Comment by thomasjgrady** [comment]
Upon further inspection, this was an issue of incorrectly installing the package using `setup.py install` instead of `pip install -e . -r requirements-dev.txt`. All tests are now passing.

**Review by thomasjgrady — APPROVED** [review]

**Pull request merged**
